services:
  backend:
    image: ghcr.io/zesty-surprise/feedback-backend:main
    pull_policy: always
    container_name: backend
    environment:
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ysp_feedback
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-network

  frontend:
    image: ghcr.io/zesty-surprise/feedback-frontend:master
    pull_policy: always
    container_name: frontend
    environment:
      BACKEND_URL: 0.0.0.0
      BACKEND_PORT: 8000
    ports:
      - "3000:3000"
    networks:
      - backend-network

volumes:
  database:

networks:
  backend-network:
    driver: bridge
