services:
  backend:
    image: ghcr.io/zesty-surprise/feedback-backend:develop
    pull_policy: always
    container_name: backend
    environment:
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/
      - MAIL_USERNAME=axel.zublena.2
      - MAIL_PASSWORD=""
      - MAIL_FROM=axel.zublena.2@gmail.com
      - MAIL_PORT=465
      - MAIL_SERVER=smtp.gmail.com
      - BACKEND_HOST=amp.test.axelzublena.com
    # Not secure, only port 465 & 8000 should be open and mapped
    # But avoid potential issue during development
    ports:
      - "8000:8000"
      - "587:587"
      - "25:25"
      - "465:465"
    expose:
      - 8000
      - 587
      - 25
      - 465
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ysp_feedback
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-network

  frontend:
    image: ghcr.io/zesty-surprise/feedback-frontend:master
    pull_policy: always
    container_name: frontend
    environment:
      BACKEND_URL: 0.0.0.0
      BACKEND_PORT: 8000
    ports:
      - "3000:3000"
    networks:
      - backend-network

volumes:
  database:

networks:
  backend-network:
    driver: bridge
